import java.io.*;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Scanner;
public class spikeFX {
    public static void main(String[] args) throws IOException
    {
        File f = new File("src/transaction.txt");
        FileReader fr = new FileReader(f);
        BufferedReader br = new BufferedReader(fr);
        String line;
        while((line = br.readLine()) != null){
            System.out.println(line);
        }
    }
}